### ISSUE TITLE
Reference to outside source example

### ISSUE THREAD

**Issue by mikaturunen** [CheckoutFinland/checkoutfinland.github.io#12]
https://checkoutfinland.github.io/ has reference to outside example sources.

> Test credentials
> 
> Merchant Id (MERCHANT): 375917
> Secret Key: SAIPPUAKAUPPIAS
> Please note that not all payment methods support testing. The payment methods are enabled that support testing payments. There might be some features that are not working as they are intended to work in the testing side due to limitations to external integrations.
> 
> The whole test code is available at: https://gist.github.com/jrasanen/2a293e7d87443e33184295fab36c96f5.
> 

Instead of having this as a single users gist file, move it into this repository into a directory called 'examples' or something and point the url into the raw static link of it from the document. This way the external document is more coherent and doesn't point to personal sources of people. 

This can be used https://help.github.com/articles/getting-permanent-links-to-files/ to make the link.

**Comment by jrasanen** [comment]
Should be done by tomorrow. Vadim's dockerizing the examples and will add live demos here along with the sources.

**Comment by jrasanen** [comment]
This was published ages ago. Closing the issue.
